import next from "@newsekolah/config/eslint/next";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...next,
  {
    ignores: [
      ".next/**",
      "next-env.d.ts",
      "playwright-report/**",
      "test-results/**",
      // Generated by serwist on each build (app/sw.ts is the real source).
      "public/**",
      // Not part of tsconfig.json's `include` (see its comment on app/sw.ts:
      // serwist bundles it separately from the Next.js/tsc type-check
      // pipeline) or type-aware at all (plain config files), so
      // typescript-eslint's project service cannot parse them.
      "app/sw.ts",
      "eslint.config.mjs",
      "postcss.config.mjs",
    ],
  },
];
