package service

import "github.com/omanjaya/newsekolah/apps/api/internal/modules/analytics/domain"

// The golden table is the recompute output captured from the original
// per-student read path (see charGolden).
func init() {
	for k, v := range map[charCase]charOutcome{
		{"default", "attendance-at-risk"}:       {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 6, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "watch", Score: 40, Reasons: []domain.ReasonCode{"attendance_absence_at_risk"}},
		{"default", "attendance-unavailable"}:   {Signals: domain.Signals{HasAttendance: false, ConsideredDays: 0, AbsentDays: 0, ActiveViolationCount: 2, DisciplinePoints: 30, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"discipline_points_watch"}},
		{"default", "attendance-watch"}:         {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 3, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 20, Reasons: []domain.ReasonCode{"attendance_absence_watch"}},
		{"default", "clean"}:                    {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"default", "discipline-at-risk"}:       {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 6, DisciplinePoints: 50, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 30, Reasons: []domain.ReasonCode{"discipline_points_at_risk"}},
		{"default", "discipline-reader-fails"}:  {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"default", "discipline-watch"}:         {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 3, DisciplinePoints: 25, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"discipline_points_watch"}},
		{"default", "everything"}:               {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 6, ActiveViolationCount: 8, DisciplinePoints: 80, WarningLetterCount: 3, HasGradeTrend: true, PreviousAverage: 90, CurrentAverage: 50}, Level: "at_risk", Score: 100, Reasons: []domain.ReasonCode{"attendance_absence_at_risk", "discipline_points_at_risk", "warning_letter_at_risk", "grade_drop_at_risk"}},
		{"default", "grade-at-risk"}:            {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: true, PreviousAverage: 85.5, CurrentAverage: 60.25}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"grade_drop_at_risk"}},
		{"default", "grade-no-drop"}:            {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: true, PreviousAverage: 70, CurrentAverage: 90}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"default", "grade-unavailable"}:        {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"default", "grade-watch"}:              {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: true, PreviousAverage: 80, CurrentAverage: 70}, Level: "none", Score: 7, Reasons: []domain.ReasonCode{"grade_drop_watch"}},
		{"default", "grading-reader-fails"}:     {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"default", "mixed-sum"}:                {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 3, ActiveViolationCount: 2, DisciplinePoints: 30, WarningLetterCount: 1, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "watch", Score: 42, Reasons: []domain.ReasonCode{"attendance_absence_watch", "discipline_points_watch", "warning_letter_watch"}},
		{"default", "warning-at-risk"}:          {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 2, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"warning_letter_at_risk"}},
		{"default", "warning-watch"}:            {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 20, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 1, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 7, Reasons: []domain.ReasonCode{"warning_letter_watch"}},
		{"window45", "attendance-at-risk"}:      {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 10, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 20, Reasons: []domain.ReasonCode{"attendance_absence_watch"}},
		{"window45", "attendance-unavailable"}:  {Signals: domain.Signals{HasAttendance: false, ConsideredDays: 0, AbsentDays: 0, ActiveViolationCount: 2, DisciplinePoints: 30, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"discipline_points_watch"}},
		{"window45", "attendance-watch"}:        {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 4, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"window45", "clean"}:                   {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"window45", "discipline-at-risk"}:      {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 6, DisciplinePoints: 50, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 30, Reasons: []domain.ReasonCode{"discipline_points_at_risk"}},
		{"window45", "discipline-reader-fails"}: {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"window45", "discipline-watch"}:        {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 3, DisciplinePoints: 25, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"discipline_points_watch"}},
		{"window45", "everything"}:              {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 10, ActiveViolationCount: 8, DisciplinePoints: 80, WarningLetterCount: 3, HasGradeTrend: true, PreviousAverage: 90, CurrentAverage: 50}, Level: "at_risk", Score: 80, Reasons: []domain.ReasonCode{"discipline_points_at_risk", "attendance_absence_watch", "warning_letter_at_risk", "grade_drop_at_risk"}},
		{"window45", "grade-at-risk"}:           {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: true, PreviousAverage: 85.5, CurrentAverage: 60.25}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"grade_drop_at_risk"}},
		{"window45", "grade-no-drop"}:           {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: true, PreviousAverage: 70, CurrentAverage: 90}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"window45", "grade-unavailable"}:       {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"window45", "grade-watch"}:             {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: true, PreviousAverage: 80, CurrentAverage: 70}, Level: "none", Score: 7, Reasons: []domain.ReasonCode{"grade_drop_watch"}},
		{"window45", "grading-reader-fails"}:    {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 0, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 0, Reasons: []domain.ReasonCode(nil)},
		{"window45", "mixed-sum"}:               {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 4, ActiveViolationCount: 2, DisciplinePoints: 30, WarningLetterCount: 1, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 22, Reasons: []domain.ReasonCode{"discipline_points_watch", "warning_letter_watch"}},
		{"window45", "warning-at-risk"}:         {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 2, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 15, Reasons: []domain.ReasonCode{"warning_letter_at_risk"}},
		{"window45", "warning-watch"}:           {Signals: domain.Signals{HasAttendance: true, ConsideredDays: 45, AbsentDays: 0, ActiveViolationCount: 0, DisciplinePoints: 0, WarningLetterCount: 1, HasGradeTrend: false, PreviousAverage: 0, CurrentAverage: 0}, Level: "none", Score: 7, Reasons: []domain.ReasonCode{"warning_letter_watch"}},
	} {
		charGolden[k] = v
	}
}
