// Generates src/message-keys.gen.ts: a union type of every leaf key in
// messages/id.json (the reference locale). Run via `pnpm codegen`, and
// automatically before `pnpm build`. See src/flatten.ts for the same
// flattening logic used at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

function flattenKeys(source: Record<string, unknown>, prefix = ""): string[] {
  const keys: string[] = [];
  for (const [key, value] of Object.entries(source)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "string") {
      keys.push(path);
    } else if (value && typeof value === "object") {
      keys.push(...flattenKeys(value as Record<string, unknown>, path));
    }
  }
  return keys;
}

const id = JSON.parse(readFileSync(resolve(root, "messages/id.json"), "utf-8")) as Record<
  string,
  unknown
>;
const keys = flattenKeys(id).sort();

const content = `// Generated by scripts/generate-types.ts from messages/id.json. Do not edit by hand.

export type MessageKey =
${keys.map((key) => `  | "${key}"`).join("\n")};

export const MESSAGE_KEYS: readonly MessageKey[] = [
${keys.map((key) => `  "${key}",`).join("\n")}
];
`;

writeFileSync(resolve(root, "src/message-keys.gen.ts"), content);
// eslint-disable-next-line no-console
console.log(`i18n: generated ${keys.length} message keys`);
