import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { StatusName, ThemeColors, TokensSource } from "./types.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const tokens = JSON.parse(readFileSync(resolve(root, "tokens.json"), "utf-8")) as TokensSource;

const STATUS_ORDER: StatusName[] = ["present", "sick", "excused", "dispensation", "absent", "late"];

function colorVars(theme: ThemeColors, indent = "  "): string[] {
  const lines = [
    `${indent}--color-bg: ${theme.bg};`,
    `${indent}--color-surface: ${theme.surface};`,
    `${indent}--color-fg: ${theme.fg};`,
    `${indent}--color-fg-muted: ${theme.fgMuted};`,
    `${indent}--color-border: ${theme.border};`,
    `${indent}--color-accent: ${theme.accent};`,
    `${indent}--color-accent-fg: ${theme.accentFg};`,
  ];
  for (const name of STATUS_ORDER) {
    const status = theme.status[name];
    lines.push(`${indent}--color-status-${name}: ${status.indicator};`);
    lines.push(`${indent}--color-status-${name}-fg: ${status.fg};`);
  }
  return lines;
}

function buildCss(): string {
  const { light, dark } = tokens.color;
  const spacing = Object.entries(tokens.spacing)
    .map(([key, value]) => `  --space-${key}: ${value}px;`)
    .join("\n");
  const radius = Object.entries(tokens.radius)
    .map(([key, value]) => `  --radius-${key}: ${value}px;`)
    .join("\n");
  const type = Object.entries(tokens.type)
    .map(([key, value]) => `  --text-${key}: ${value}px;`)
    .join("\n");
  const zIndex = Object.entries(tokens.zIndex)
    .map(([key, value]) => `  --z-${key}: ${value};`)
    .join("\n");
  const shadow = Object.entries(tokens.shadow)
    .map(([key, value]) => `  --shadow-${key}: ${value};`)
    .join("\n");

  return `/* Generated by packages/ui-tokens/scripts/build-tokens.ts. Do not edit by hand. */

:root {
${colorVars(light).join("\n")}
${spacing}
${radius}
${type}
${zIndex}
${shadow}
  --duration-fast: ${tokens.motion.duration.fast}ms;
  --duration-base: ${tokens.motion.duration.base}ms;
  --ease-standard: ${tokens.motion.easing};
}

[data-theme="dark"] {
${colorVars(dark).join("\n")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars(dark, "    ").join("\n")}
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
  }
}
`;
}

function themeObjectLiteral(theme: ThemeColors): string {
  const statusEntries = STATUS_ORDER.map(
    (name) =>
      `      ${name}: { indicator: "${theme.status[name].indicator}", fg: "${theme.status[name].fg}" }`,
  ).join(",\n");
  return `{
    bg: "${theme.bg}",
    surface: "${theme.surface}",
    fg: "${theme.fg}",
    fgMuted: "${theme.fgMuted}",
    border: "${theme.border}",
    accent: "${theme.accent}",
    accentFg: "${theme.accentFg}",
    status: {
${statusEntries},
    },
  }`;
}

function buildTs(): string {
  const { light, dark } = tokens.color;
  return `// Generated by packages/ui-tokens/scripts/build-tokens.ts. Do not edit by hand.
// Typed token object for NativeWind / React Native, mirroring dist/tokens.css.

export type StatusName = "present" | "sick" | "excused" | "dispensation" | "absent" | "late";

export interface StatusColor {
  indicator: string;
  fg: string;
}

export interface ThemeColors {
  bg: string;
  surface: string;
  fg: string;
  fgMuted: string;
  border: string;
  accent: string;
  accentFg: string;
  status: Record<StatusName, StatusColor>;
}

export const statusNames: Record<StatusName, string> = ${JSON.stringify(tokens.statusNames, null, 2).replace(/\n/g, "\n  ")};

export const colors = {
  light: ${themeObjectLiteral(light)},
  dark: ${themeObjectLiteral(dark)},
} satisfies Record<"light" | "dark", ThemeColors>;

export const spacing = ${JSON.stringify(tokens.spacing, null, 2).replace(/\n/g, "\n  ")} as const;

export const radius = ${JSON.stringify(tokens.radius, null, 2).replace(/\n/g, "\n  ")} as const;

export const type = ${JSON.stringify(tokens.type, null, 2).replace(/\n/g, "\n  ")} as const;

export const shadow = ${JSON.stringify(tokens.shadow, null, 2).replace(/\n/g, "\n  ")} as const;

export const zIndex = ${JSON.stringify(tokens.zIndex, null, 2).replace(/\n/g, "\n  ")} as const;

export const motion = ${JSON.stringify(tokens.motion, null, 2).replace(/\n/g, "\n  ")} as const;
`;
}

const distDir = resolve(root, "dist");
mkdirSync(distDir, { recursive: true });
writeFileSync(resolve(distDir, "tokens.css"), buildCss());
writeFileSync(resolve(distDir, "tokens.ts"), buildTs());

// eslint-disable-next-line no-console
console.log("ui-tokens: wrote dist/tokens.css and dist/tokens.ts");
