package httpx

import "net/http"

var (
	ErrLibraryTitleNotFound          = NewError(http.StatusNotFound, "LIBRARY_TITLE_NOT_FOUND")
	ErrLibraryCopyNotFound           = NewError(http.StatusNotFound, "LIBRARY_COPY_NOT_FOUND")
	ErrLibraryCopyBarcodeExists      = NewError(http.StatusConflict, "LIBRARY_COPY_BARCODE_EXISTS")
	ErrLibraryCopyNotAvailable       = NewError(http.StatusConflict, "LIBRARY_COPY_NOT_AVAILABLE")
	ErrLibraryCopyOnLoan             = NewError(http.StatusConflict, "LIBRARY_COPY_ON_LOAN")
	ErrLibraryLoanNotFound           = NewError(http.StatusNotFound, "LIBRARY_LOAN_NOT_FOUND")
	ErrLibraryLoanAlreadyReturned    = NewError(http.StatusConflict, "LIBRARY_LOAN_ALREADY_RETURNED")
	ErrLibraryLoanLimitReached       = NewError(http.StatusConflict, "LIBRARY_LOAN_LIMIT_REACHED")
	ErrLibraryRenewalLimitReached    = NewError(http.StatusConflict, "LIBRARY_RENEWAL_LIMIT_REACHED")
	ErrLibraryRenewalBlockedOverdue  = NewError(http.StatusConflict, "LIBRARY_RENEWAL_BLOCKED_OVERDUE")
	ErrLibraryRenewalBlockedReserved = NewError(http.StatusConflict, "LIBRARY_RENEWAL_BLOCKED_RESERVED")
	ErrLibraryReservationNotFound    = NewError(http.StatusNotFound, "LIBRARY_RESERVATION_NOT_FOUND")
	ErrLibraryReservationNotWaiting  = NewError(http.StatusConflict, "LIBRARY_RESERVATION_NOT_WAITING")
	ErrLibraryCopyAvailableForLoan   = NewError(http.StatusConflict, "LIBRARY_COPY_AVAILABLE_FOR_LOAN")
	ErrLibraryStocktakeNotFound      = NewError(http.StatusNotFound, "LIBRARY_STOCKTAKE_NOT_FOUND")
	ErrLibraryStocktakeClosed        = NewError(http.StatusConflict, "LIBRARY_STOCKTAKE_CLOSED")
	ErrLibraryTitleHasCopies         = NewError(http.StatusConflict, "LIBRARY_TITLE_HAS_COPIES")
	ErrLibraryControlNumberExists    = NewError(http.StatusConflict, "LIBRARY_CONTROL_NUMBER_EXISTS")
	ErrLibraryCopyAccessionExists    = NewError(http.StatusConflict, "LIBRARY_COPY_ACCESSION_EXISTS")
	ErrLibraryCopyHasLoanHistory     = NewError(http.StatusConflict, "LIBRARY_COPY_HAS_LOAN_HISTORY")
	ErrLibraryCopyStatusNotManual    = NewError(http.StatusConflict, "LIBRARY_COPY_STATUS_NOT_MANUAL")
	ErrLibraryMasterDataNotFound     = NewError(http.StatusNotFound, "LIBRARY_MASTER_DATA_NOT_FOUND")
	ErrLibraryMasterDataCodeExists   = NewError(http.StatusConflict, "LIBRARY_MASTER_DATA_CODE_EXISTS")
	ErrLibraryMasterDataInUse        = NewError(http.StatusConflict, "LIBRARY_MASTER_DATA_IN_USE")

	ErrLibraryModuleDisabled = NewError(http.StatusNotFound, "LIBRARY_MODULE_DISABLED")
	ErrLibraryLoansClosed    = NewError(http.StatusConflict, "LIBRARY_LOANS_CLOSED")
	ErrLibraryUnpaidFine     = NewError(http.StatusConflict, "LIBRARY_UNPAID_FINE")
	ErrLibraryForbidden      = NewError(http.StatusForbidden, "LIBRARY_FORBIDDEN")

	ErrLibraryMemberNotFound      = NewError(http.StatusNotFound, "LIBRARY_MEMBER_NOT_FOUND")
	ErrLibraryMemberAlreadyExists = NewError(http.StatusConflict, "LIBRARY_MEMBER_ALREADY_EXISTS")
	ErrLibraryMemberNotActive     = NewError(http.StatusConflict, "LIBRARY_MEMBER_NOT_ACTIVE")
	ErrLibraryMemberSuspended     = NewError(http.StatusConflict, "LIBRARY_MEMBER_SUSPENDED")
	ErrLibraryMemberExpired       = NewError(http.StatusConflict, "LIBRARY_MEMBER_EXPIRED")
	ErrLibraryMemberNotClearable  = NewError(http.StatusConflict, "LIBRARY_MEMBER_NOT_CLEARABLE")
	ErrLibraryMemberTypeNotFound  = NewError(http.StatusNotFound, "LIBRARY_MEMBER_TYPE_NOT_FOUND")
	ErrLibraryMemberTypeInUse     = NewError(http.StatusConflict, "LIBRARY_MEMBER_TYPE_IN_USE")
	ErrLibraryMemberNoExhausted   = NewError(http.StatusConflict, "LIBRARY_MEMBER_NO_EXHAUSTED")
	ErrLibraryMemberNoCollision   = NewError(http.StatusConflict, "LIBRARY_MEMBER_NO_COLLISION")

	ErrLibraryViolationNotFound       = NewError(http.StatusNotFound, "LIBRARY_VIOLATION_NOT_FOUND")
	ErrLibraryViolationAlreadySettled = NewError(http.StatusConflict, "LIBRARY_VIOLATION_ALREADY_SETTLED")

	ErrLibraryVisitNotFound = NewError(http.StatusNotFound, "LIBRARY_VISIT_NOT_FOUND")

	ErrLibraryCoverTooLarge      = NewError(http.StatusBadRequest, "LIBRARY_COVER_TOO_LARGE")
	ErrLibraryCoverInvalidType   = NewError(http.StatusBadRequest, "LIBRARY_COVER_INVALID_TYPE")
	ErrLibraryStorageUnavailable = NewError(http.StatusServiceUnavailable, "LIBRARY_STORAGE_UNAVAILABLE")
)
