// Generated by scripts/generate-types.ts from messages/id.json. Do not edit by hand.

export type MessageKey =
  | "auth.changePassword.confirmLabel"
  | "auth.changePassword.currentLabel"
  | "auth.changePassword.newLabel"
  | "auth.changePassword.submit"
  | "auth.changePassword.success"
  | "auth.changePassword.title"
  | "auth.login.passwordLabel"
  | "auth.login.submit"
  | "auth.login.submitting"
  | "auth.login.tenantLabel"
  | "auth.login.title"
  | "auth.login.usernameLabel"
  | "auth.sessions.currentDevice"
  | "auth.sessions.lastSeen"
  | "auth.sessions.revoke"
  | "auth.sessions.revokeConfirmBody"
  | "auth.sessions.revokeConfirmTitle"
  | "auth.sessions.title"
  | "common.actions.add"
  | "common.actions.back"
  | "common.actions.cancel"
  | "common.actions.clearFilter"
  | "common.actions.close"
  | "common.actions.confirm"
  | "common.actions.copy"
  | "common.actions.create"
  | "common.actions.delete"
  | "common.actions.done"
  | "common.actions.download"
  | "common.actions.edit"
  | "common.actions.export"
  | "common.actions.filter"
  | "common.actions.import"
  | "common.actions.logout"
  | "common.actions.next"
  | "common.actions.print"
  | "common.actions.retry"
  | "common.actions.save"
  | "common.actions.search"
  | "common.actions.viewAll"
  | "common.actions.viewDetail"
  | "common.confirmDialog.defaultCancelLabel"
  | "common.confirmDialog.defaultConfirmLabel"
  | "common.confirmDialog.defaultTitle"
  | "common.states.empty"
  | "common.states.error"
  | "common.states.loading"
  | "common.states.noResults"
  | "common.states.offline"
  | "common.states.saved"
  | "common.states.unsavedChanges"
  | "common.table.columnVisibility"
  | "common.table.densityCompact"
  | "common.table.densityNormal"
  | "common.table.goToNextPage"
  | "common.table.goToPreviousPage"
  | "common.table.page"
  | "common.table.rowsSelected"
  | "errors.AUTH_INVALID_CREDENTIALS"
  | "errors.AUTH_TOKEN_EXPIRED"
  | "errors.FORBIDDEN"
  | "errors.NETWORK"
  | "errors.NOT_FOUND"
  | "errors.RATE_LIMITED"
  | "errors.TENANT_NOT_FOUND"
  | "errors.UNKNOWN"
  | "errors.VALIDATION_FAILED"
  | "nav.academic.items.attendance"
  | "nav.academic.items.grading"
  | "nav.academic.items.homeroomClass"
  | "nav.academic.items.journal"
  | "nav.academic.items.schedule"
  | "nav.academic.items.substituteTeacher"
  | "nav.academic.label"
  | "nav.communication.items.announcements"
  | "nav.communication.items.notifications"
  | "nav.communication.label"
  | "nav.compact.announcements"
  | "nav.compact.attendance"
  | "nav.compact.grades"
  | "nav.compact.library"
  | "nav.compact.permits"
  | "nav.compact.profile"
  | "nav.discipline.items.counseling"
  | "nav.discipline.items.reports"
  | "nav.discipline.items.violations"
  | "nav.discipline.items.warningLetters"
  | "nav.discipline.label"
  | "nav.home"
  | "nav.library.items.catalog"
  | "nav.library.items.circulation"
  | "nav.library.items.members"
  | "nav.library.items.opac"
  | "nav.library.items.reports"
  | "nav.library.items.stockOpname"
  | "nav.library.items.visits"
  | "nav.library.label"
  | "nav.permits.items.exitPermit"
  | "nav.permits.items.gate"
  | "nav.permits.items.late"
  | "nav.permits.items.plannedLeave"
  | "nav.permits.items.verification"
  | "nav.permits.label"
  | "nav.schoolData.items.academicYear"
  | "nav.schoolData.items.assignments"
  | "nav.schoolData.items.classesAndStudents"
  | "nav.schoolData.items.periods"
  | "nav.schoolData.items.rooms"
  | "nav.schoolData.items.subjects"
  | "nav.schoolData.items.teachersAndStaff"
  | "nav.schoolData.items.violationCatalog"
  | "nav.schoolData.label"
  | "nav.settings.items.documentTemplates"
  | "nav.settings.items.integrations"
  | "nav.settings.items.modules"
  | "nav.settings.items.policies"
  | "nav.settings.items.rolesAndAccess"
  | "nav.settings.items.schoolProfile"
  | "nav.settings.items.sessionsAndSecurity"
  | "nav.settings.label"
  | "validation.email"
  | "validation.maxLength"
  | "validation.minLength"
  | "validation.passwordMax"
  | "validation.passwordMin"
  | "validation.passwordMismatch"
  | "validation.passwordRequired"
  | "validation.required"
  | "validation.tenantQueryMin"
  | "validation.usernameRequired";

export const MESSAGE_KEYS: readonly MessageKey[] = [
  "auth.changePassword.confirmLabel",
  "auth.changePassword.currentLabel",
  "auth.changePassword.newLabel",
  "auth.changePassword.submit",
  "auth.changePassword.success",
  "auth.changePassword.title",
  "auth.login.passwordLabel",
  "auth.login.submit",
  "auth.login.submitting",
  "auth.login.tenantLabel",
  "auth.login.title",
  "auth.login.usernameLabel",
  "auth.sessions.currentDevice",
  "auth.sessions.lastSeen",
  "auth.sessions.revoke",
  "auth.sessions.revokeConfirmBody",
  "auth.sessions.revokeConfirmTitle",
  "auth.sessions.title",
  "common.actions.add",
  "common.actions.back",
  "common.actions.cancel",
  "common.actions.clearFilter",
  "common.actions.close",
  "common.actions.confirm",
  "common.actions.copy",
  "common.actions.create",
  "common.actions.delete",
  "common.actions.done",
  "common.actions.download",
  "common.actions.edit",
  "common.actions.export",
  "common.actions.filter",
  "common.actions.import",
  "common.actions.logout",
  "common.actions.next",
  "common.actions.print",
  "common.actions.retry",
  "common.actions.save",
  "common.actions.search",
  "common.actions.viewAll",
  "common.actions.viewDetail",
  "common.confirmDialog.defaultCancelLabel",
  "common.confirmDialog.defaultConfirmLabel",
  "common.confirmDialog.defaultTitle",
  "common.states.empty",
  "common.states.error",
  "common.states.loading",
  "common.states.noResults",
  "common.states.offline",
  "common.states.saved",
  "common.states.unsavedChanges",
  "common.table.columnVisibility",
  "common.table.densityCompact",
  "common.table.densityNormal",
  "common.table.goToNextPage",
  "common.table.goToPreviousPage",
  "common.table.page",
  "common.table.rowsSelected",
  "errors.AUTH_INVALID_CREDENTIALS",
  "errors.AUTH_TOKEN_EXPIRED",
  "errors.FORBIDDEN",
  "errors.NETWORK",
  "errors.NOT_FOUND",
  "errors.RATE_LIMITED",
  "errors.TENANT_NOT_FOUND",
  "errors.UNKNOWN",
  "errors.VALIDATION_FAILED",
  "nav.academic.items.attendance",
  "nav.academic.items.grading",
  "nav.academic.items.homeroomClass",
  "nav.academic.items.journal",
  "nav.academic.items.schedule",
  "nav.academic.items.substituteTeacher",
  "nav.academic.label",
  "nav.communication.items.announcements",
  "nav.communication.items.notifications",
  "nav.communication.label",
  "nav.compact.announcements",
  "nav.compact.attendance",
  "nav.compact.grades",
  "nav.compact.library",
  "nav.compact.permits",
  "nav.compact.profile",
  "nav.discipline.items.counseling",
  "nav.discipline.items.reports",
  "nav.discipline.items.violations",
  "nav.discipline.items.warningLetters",
  "nav.discipline.label",
  "nav.home",
  "nav.library.items.catalog",
  "nav.library.items.circulation",
  "nav.library.items.members",
  "nav.library.items.opac",
  "nav.library.items.reports",
  "nav.library.items.stockOpname",
  "nav.library.items.visits",
  "nav.library.label",
  "nav.permits.items.exitPermit",
  "nav.permits.items.gate",
  "nav.permits.items.late",
  "nav.permits.items.plannedLeave",
  "nav.permits.items.verification",
  "nav.permits.label",
  "nav.schoolData.items.academicYear",
  "nav.schoolData.items.assignments",
  "nav.schoolData.items.classesAndStudents",
  "nav.schoolData.items.periods",
  "nav.schoolData.items.rooms",
  "nav.schoolData.items.subjects",
  "nav.schoolData.items.teachersAndStaff",
  "nav.schoolData.items.violationCatalog",
  "nav.schoolData.label",
  "nav.settings.items.documentTemplates",
  "nav.settings.items.integrations",
  "nav.settings.items.modules",
  "nav.settings.items.policies",
  "nav.settings.items.rolesAndAccess",
  "nav.settings.items.schoolProfile",
  "nav.settings.items.sessionsAndSecurity",
  "nav.settings.label",
  "validation.email",
  "validation.maxLength",
  "validation.minLength",
  "validation.passwordMax",
  "validation.passwordMin",
  "validation.passwordMismatch",
  "validation.passwordRequired",
  "validation.required",
  "validation.tenantQueryMin",
  "validation.usernameRequired",
];
