// Generated by scripts/generate-types.ts from messages/id.json. Do not edit by hand.

export type MessageKey =
  | "auth.changePassword.confirmLabel"
  | "auth.changePassword.currentLabel"
  | "auth.changePassword.newLabel"
  | "auth.changePassword.submit"
  | "auth.changePassword.success"
  | "auth.changePassword.title"
  | "auth.login.backToPassword"
  | "auth.login.forgotPasswordLink"
  | "auth.login.googleButton"
  | "auth.login.orDivider"
  | "auth.login.passkeyButton"
  | "auth.login.passkeyUsernameRequired"
  | "auth.login.passwordLabel"
  | "auth.login.submit"
  | "auth.login.submitting"
  | "auth.login.tenantLabel"
  | "auth.login.title"
  | "auth.login.usernameLabel"
  | "auth.sessions.currentDevice"
  | "auth.sessions.lastSeen"
  | "auth.sessions.revoke"
  | "auth.sessions.revokeConfirmBody"
  | "auth.sessions.revokeConfirmTitle"
  | "auth.sessions.title"
  | "common.actions.add"
  | "common.actions.back"
  | "common.actions.cancel"
  | "common.actions.clearFilter"
  | "common.actions.close"
  | "common.actions.confirm"
  | "common.actions.copy"
  | "common.actions.create"
  | "common.actions.delete"
  | "common.actions.done"
  | "common.actions.download"
  | "common.actions.edit"
  | "common.actions.export"
  | "common.actions.filter"
  | "common.actions.import"
  | "common.actions.logout"
  | "common.actions.next"
  | "common.actions.print"
  | "common.actions.retry"
  | "common.actions.save"
  | "common.actions.search"
  | "common.actions.viewAll"
  | "common.actions.viewDetail"
  | "common.confirmDialog.defaultCancelLabel"
  | "common.confirmDialog.defaultConfirmLabel"
  | "common.confirmDialog.defaultTitle"
  | "common.states.empty"
  | "common.states.error"
  | "common.states.loading"
  | "common.states.noResults"
  | "common.states.offline"
  | "common.states.saved"
  | "common.states.unsavedChanges"
  | "common.table.columnVisibility"
  | "common.table.densityCompact"
  | "common.table.densityNormal"
  | "common.table.goToNextPage"
  | "common.table.goToPreviousPage"
  | "common.table.page"
  | "common.table.rowsSelected"
  | "errors.ATTACHMENT_INVALID_TYPE"
  | "errors.ATTACHMENT_NOT_FOUND"
  | "errors.ATTACHMENT_TOO_LARGE"
  | "errors.AUTH_INVALID_CREDENTIALS"
  | "errors.AUTH_TOKEN_EXPIRED"
  | "errors.BILLING_MODULE_DISABLED"
  | "errors.BILL_ALREADY_PAID"
  | "errors.BILL_NOT_FOUND"
  | "errors.COUNSELING_FORBIDDEN"
  | "errors.DISCOUNT_NOT_FOUND"
  | "errors.DUTY_TYPE_IN_USE"
  | "errors.EXPECTED_GUEST_NOT_FOUND"
  | "errors.EXPECTED_GUEST_RESOLVED"
  | "errors.FEE_TYPE_NOT_FOUND"
  | "errors.FORBIDDEN"
  | "errors.GRADE_RANGE_OVERLAP"
  | "errors.IMPERSONATION_NOT_ALLOWED"
  | "errors.INCIDENT_ALREADY_CLOSED"
  | "errors.INCIDENT_FORBIDDEN"
  | "errors.INCIDENT_NOT_FOUND"
  | "errors.LIBRARY_COPY_AVAILABLE_FOR_LOAN"
  | "errors.LIBRARY_COPY_BARCODE_EXISTS"
  | "errors.LIBRARY_COPY_NOT_AVAILABLE"
  | "errors.LIBRARY_COPY_NOT_FOUND"
  | "errors.LIBRARY_COPY_ON_LOAN"
  | "errors.LIBRARY_LOAN_ALREADY_RETURNED"
  | "errors.LIBRARY_LOAN_LIMIT_REACHED"
  | "errors.LIBRARY_LOAN_NOT_FOUND"
  | "errors.LIBRARY_RENEWAL_BLOCKED_OVERDUE"
  | "errors.LIBRARY_RENEWAL_BLOCKED_RESERVED"
  | "errors.LIBRARY_RENEWAL_LIMIT_REACHED"
  | "errors.LIBRARY_RESERVATION_NOT_FOUND"
  | "errors.LIBRARY_RESERVATION_NOT_WAITING"
  | "errors.LIBRARY_STOCKTAKE_CLOSED"
  | "errors.LIBRARY_STOCKTAKE_NOT_FOUND"
  | "errors.LIBRARY_TITLE_NOT_FOUND"
  | "errors.MENTORING_MODULE_DISABLED"
  | "errors.MENTOR_GROUP_FULL"
  | "errors.MENTOR_GROUP_NOT_FOUND"
  | "errors.MENTOR_MEMBER_ALREADY_IN_GROUP"
  | "errors.MENTOR_NOTE_FORBIDDEN"
  | "errors.MENTOR_NOTE_NOT_FOUND"
  | "errors.MENTOR_SUMMARY_NOT_FOUND"
  | "errors.MODULE_DISABLED"
  | "errors.NETWORK"
  | "errors.NOT_FOUND"
  | "errors.NOT_IMPERSONATING"
  | "errors.PASSKEY_CHALLENGE_EXPIRED"
  | "errors.PASSKEY_INVALID_RESPONSE"
  | "errors.PASSKEY_NOT_CONFIGURED"
  | "errors.PASSKEY_NOT_FOUND"
  | "errors.PASSWORD_RESET_TOKEN_INVALID"
  | "errors.PAYMENT_ALREADY_VOIDED"
  | "errors.PAYMENT_EXCEEDS_OUTSTANDING"
  | "errors.PAYMENT_NOT_FOUND"
  | "errors.RATE_LIMITED"
  | "errors.REPORT_UNAVAILABLE"
  | "errors.SSO_ACCOUNT_NOT_FOUND"
  | "errors.SSO_CLIENT_SECRET_REQUIRED"
  | "errors.SSO_INVALID_TOKEN"
  | "errors.SSO_NOT_CONFIGURED"
  | "errors.STAFF_ATTENDANCE_ALREADY_SCANNED"
  | "errors.STAFF_ATTENDANCE_CORRECTION_REASON_REQUIRED"
  | "errors.STAFF_ATTENDANCE_INVALID_MONTH"
  | "errors.STAFF_ATTENDANCE_SCHEDULE_DAY_INVALID"
  | "errors.SUPERVISION_CYCLE_NOT_FOUND"
  | "errors.SUPERVISION_INSTRUMENT_INVALID"
  | "errors.SUPERVISION_LESSON_NOT_RESOLVED"
  | "errors.SUPERVISION_MODULE_DISABLED"
  | "errors.SUPERVISION_OBSERVATION_FORBIDDEN"
  | "errors.SUPERVISION_OBSERVATION_NOT_FOUND"
  | "errors.SUPERVISION_SCHEDULED_ALREADY_DONE"
  | "errors.SUPERVISION_SCHEDULED_NOT_FOUND"
  | "errors.SUPERVISION_SCORE_COUNT_MISMATCH"
  | "errors.SUPERVISION_SCORE_OUT_OF_RANGE"
  | "errors.TENANT_NOT_FOUND"
  | "errors.TP_EXPORT_CODE_EXISTS"
  | "errors.TP_KIND_NOT_ELIGIBLE"
  | "errors.UNKNOWN"
  | "errors.UPLOAD_FILE_TOO_LARGE"
  | "errors.UPLOAD_INVALID_FILE_TYPE"
  | "errors.UPLOAD_NOT_CONFIGURED"
  | "errors.USER_ALREADY_EXISTS"
  | "errors.VALIDATION_FAILED"
  | "errors.VIOLATION_RECORD_VOIDED"
  | "errors.VIOLATION_TYPE_INACTIVE"
  | "errors.VISITORS_MODULE_DISABLED"
  | "errors.VISIT_ALREADY_CHECKED_OUT"
  | "errors.VISIT_NOT_FOUND"
  | "errors.WARNING_LETTER_ALREADY_ISSUED"
  | "errors.WARNING_LETTER_NOT_DUE"
  | "nav.academic.items.attendance"
  | "nav.academic.items.grading"
  | "nav.academic.items.homeroomClass"
  | "nav.academic.items.journal"
  | "nav.academic.items.schedule"
  | "nav.academic.items.substituteTeacher"
  | "nav.academic.label"
  | "nav.activities.label"
  | "nav.communication.items.announcements"
  | "nav.communication.items.notifications"
  | "nav.communication.label"
  | "nav.compact.announcements"
  | "nav.compact.attendance"
  | "nav.compact.grades"
  | "nav.compact.library"
  | "nav.compact.permits"
  | "nav.compact.profile"
  | "nav.discipline.items.counseling"
  | "nav.discipline.items.reports"
  | "nav.discipline.items.violations"
  | "nav.discipline.items.warningLetters"
  | "nav.discipline.label"
  | "nav.finance.label"
  | "nav.home"
  | "nav.library.items.catalog"
  | "nav.library.items.circulation"
  | "nav.library.items.members"
  | "nav.library.items.opac"
  | "nav.library.items.reports"
  | "nav.library.items.stockOpname"
  | "nav.library.items.visits"
  | "nav.library.label"
  | "nav.mentoring.label"
  | "nav.permits.items.exitPermit"
  | "nav.permits.items.gate"
  | "nav.permits.items.late"
  | "nav.permits.items.plannedLeave"
  | "nav.permits.items.verification"
  | "nav.permits.label"
  | "nav.platform.items.tenants"
  | "nav.platform.label"
  | "nav.schoolData.items.academicCalendar"
  | "nav.schoolData.items.academicYear"
  | "nav.schoolData.items.assignments"
  | "nav.schoolData.items.classesAndStudents"
  | "nav.schoolData.items.enrollmentImport"
  | "nav.schoolData.items.gradeLevels"
  | "nav.schoolData.items.newYearSetup"
  | "nav.schoolData.items.periods"
  | "nav.schoolData.items.promotion"
  | "nav.schoolData.items.rooms"
  | "nav.schoolData.items.subjectOfferings"
  | "nav.schoolData.items.subjects"
  | "nav.schoolData.items.teachersAndStaff"
  | "nav.schoolData.items.teachingAssignments"
  | "nav.schoolData.items.tracks"
  | "nav.schoolData.items.violationCatalog"
  | "nav.schoolData.label"
  | "nav.settings.items.documentTemplates"
  | "nav.settings.items.integrations"
  | "nav.settings.items.modules"
  | "nav.settings.items.policies"
  | "nav.settings.items.rolesAndAccess"
  | "nav.settings.items.schoolProfile"
  | "nav.settings.items.sessionsAndSecurity"
  | "nav.settings.label"
  | "nav.supervision.label"
  | "nav.visitors.items.board"
  | "nav.visitors.items.expected"
  | "nav.visitors.items.incidents"
  | "nav.visitors.items.reports"
  | "nav.visitors.label"
  | "validation.email"
  | "validation.maxLength"
  | "validation.minLength"
  | "validation.passwordMax"
  | "validation.passwordMin"
  | "validation.passwordMismatch"
  | "validation.passwordRequired"
  | "validation.required"
  | "validation.tenantQueryMin"
  | "validation.usernameRequired";

export const MESSAGE_KEYS: readonly MessageKey[] = [
  "auth.changePassword.confirmLabel",
  "auth.changePassword.currentLabel",
  "auth.changePassword.newLabel",
  "auth.changePassword.submit",
  "auth.changePassword.success",
  "auth.changePassword.title",
  "auth.login.backToPassword",
  "auth.login.forgotPasswordLink",
  "auth.login.googleButton",
  "auth.login.orDivider",
  "auth.login.passkeyButton",
  "auth.login.passkeyUsernameRequired",
  "auth.login.passwordLabel",
  "auth.login.submit",
  "auth.login.submitting",
  "auth.login.tenantLabel",
  "auth.login.title",
  "auth.login.usernameLabel",
  "auth.sessions.currentDevice",
  "auth.sessions.lastSeen",
  "auth.sessions.revoke",
  "auth.sessions.revokeConfirmBody",
  "auth.sessions.revokeConfirmTitle",
  "auth.sessions.title",
  "common.actions.add",
  "common.actions.back",
  "common.actions.cancel",
  "common.actions.clearFilter",
  "common.actions.close",
  "common.actions.confirm",
  "common.actions.copy",
  "common.actions.create",
  "common.actions.delete",
  "common.actions.done",
  "common.actions.download",
  "common.actions.edit",
  "common.actions.export",
  "common.actions.filter",
  "common.actions.import",
  "common.actions.logout",
  "common.actions.next",
  "common.actions.print",
  "common.actions.retry",
  "common.actions.save",
  "common.actions.search",
  "common.actions.viewAll",
  "common.actions.viewDetail",
  "common.confirmDialog.defaultCancelLabel",
  "common.confirmDialog.defaultConfirmLabel",
  "common.confirmDialog.defaultTitle",
  "common.states.empty",
  "common.states.error",
  "common.states.loading",
  "common.states.noResults",
  "common.states.offline",
  "common.states.saved",
  "common.states.unsavedChanges",
  "common.table.columnVisibility",
  "common.table.densityCompact",
  "common.table.densityNormal",
  "common.table.goToNextPage",
  "common.table.goToPreviousPage",
  "common.table.page",
  "common.table.rowsSelected",
  "errors.ATTACHMENT_INVALID_TYPE",
  "errors.ATTACHMENT_NOT_FOUND",
  "errors.ATTACHMENT_TOO_LARGE",
  "errors.AUTH_INVALID_CREDENTIALS",
  "errors.AUTH_TOKEN_EXPIRED",
  "errors.BILLING_MODULE_DISABLED",
  "errors.BILL_ALREADY_PAID",
  "errors.BILL_NOT_FOUND",
  "errors.COUNSELING_FORBIDDEN",
  "errors.DISCOUNT_NOT_FOUND",
  "errors.DUTY_TYPE_IN_USE",
  "errors.EXPECTED_GUEST_NOT_FOUND",
  "errors.EXPECTED_GUEST_RESOLVED",
  "errors.FEE_TYPE_NOT_FOUND",
  "errors.FORBIDDEN",
  "errors.GRADE_RANGE_OVERLAP",
  "errors.IMPERSONATION_NOT_ALLOWED",
  "errors.INCIDENT_ALREADY_CLOSED",
  "errors.INCIDENT_FORBIDDEN",
  "errors.INCIDENT_NOT_FOUND",
  "errors.LIBRARY_COPY_AVAILABLE_FOR_LOAN",
  "errors.LIBRARY_COPY_BARCODE_EXISTS",
  "errors.LIBRARY_COPY_NOT_AVAILABLE",
  "errors.LIBRARY_COPY_NOT_FOUND",
  "errors.LIBRARY_COPY_ON_LOAN",
  "errors.LIBRARY_LOAN_ALREADY_RETURNED",
  "errors.LIBRARY_LOAN_LIMIT_REACHED",
  "errors.LIBRARY_LOAN_NOT_FOUND",
  "errors.LIBRARY_RENEWAL_BLOCKED_OVERDUE",
  "errors.LIBRARY_RENEWAL_BLOCKED_RESERVED",
  "errors.LIBRARY_RENEWAL_LIMIT_REACHED",
  "errors.LIBRARY_RESERVATION_NOT_FOUND",
  "errors.LIBRARY_RESERVATION_NOT_WAITING",
  "errors.LIBRARY_STOCKTAKE_CLOSED",
  "errors.LIBRARY_STOCKTAKE_NOT_FOUND",
  "errors.LIBRARY_TITLE_NOT_FOUND",
  "errors.MENTORING_MODULE_DISABLED",
  "errors.MENTOR_GROUP_FULL",
  "errors.MENTOR_GROUP_NOT_FOUND",
  "errors.MENTOR_MEMBER_ALREADY_IN_GROUP",
  "errors.MENTOR_NOTE_FORBIDDEN",
  "errors.MENTOR_NOTE_NOT_FOUND",
  "errors.MENTOR_SUMMARY_NOT_FOUND",
  "errors.MODULE_DISABLED",
  "errors.NETWORK",
  "errors.NOT_FOUND",
  "errors.NOT_IMPERSONATING",
  "errors.PASSKEY_CHALLENGE_EXPIRED",
  "errors.PASSKEY_INVALID_RESPONSE",
  "errors.PASSKEY_NOT_CONFIGURED",
  "errors.PASSKEY_NOT_FOUND",
  "errors.PASSWORD_RESET_TOKEN_INVALID",
  "errors.PAYMENT_ALREADY_VOIDED",
  "errors.PAYMENT_EXCEEDS_OUTSTANDING",
  "errors.PAYMENT_NOT_FOUND",
  "errors.RATE_LIMITED",
  "errors.REPORT_UNAVAILABLE",
  "errors.SSO_ACCOUNT_NOT_FOUND",
  "errors.SSO_CLIENT_SECRET_REQUIRED",
  "errors.SSO_INVALID_TOKEN",
  "errors.SSO_NOT_CONFIGURED",
  "errors.STAFF_ATTENDANCE_ALREADY_SCANNED",
  "errors.STAFF_ATTENDANCE_CORRECTION_REASON_REQUIRED",
  "errors.STAFF_ATTENDANCE_INVALID_MONTH",
  "errors.STAFF_ATTENDANCE_SCHEDULE_DAY_INVALID",
  "errors.SUPERVISION_CYCLE_NOT_FOUND",
  "errors.SUPERVISION_INSTRUMENT_INVALID",
  "errors.SUPERVISION_LESSON_NOT_RESOLVED",
  "errors.SUPERVISION_MODULE_DISABLED",
  "errors.SUPERVISION_OBSERVATION_FORBIDDEN",
  "errors.SUPERVISION_OBSERVATION_NOT_FOUND",
  "errors.SUPERVISION_SCHEDULED_ALREADY_DONE",
  "errors.SUPERVISION_SCHEDULED_NOT_FOUND",
  "errors.SUPERVISION_SCORE_COUNT_MISMATCH",
  "errors.SUPERVISION_SCORE_OUT_OF_RANGE",
  "errors.TENANT_NOT_FOUND",
  "errors.TP_EXPORT_CODE_EXISTS",
  "errors.TP_KIND_NOT_ELIGIBLE",
  "errors.UNKNOWN",
  "errors.UPLOAD_FILE_TOO_LARGE",
  "errors.UPLOAD_INVALID_FILE_TYPE",
  "errors.UPLOAD_NOT_CONFIGURED",
  "errors.USER_ALREADY_EXISTS",
  "errors.VALIDATION_FAILED",
  "errors.VIOLATION_RECORD_VOIDED",
  "errors.VIOLATION_TYPE_INACTIVE",
  "errors.VISITORS_MODULE_DISABLED",
  "errors.VISIT_ALREADY_CHECKED_OUT",
  "errors.VISIT_NOT_FOUND",
  "errors.WARNING_LETTER_ALREADY_ISSUED",
  "errors.WARNING_LETTER_NOT_DUE",
  "nav.academic.items.attendance",
  "nav.academic.items.grading",
  "nav.academic.items.homeroomClass",
  "nav.academic.items.journal",
  "nav.academic.items.schedule",
  "nav.academic.items.substituteTeacher",
  "nav.academic.label",
  "nav.activities.label",
  "nav.communication.items.announcements",
  "nav.communication.items.notifications",
  "nav.communication.label",
  "nav.compact.announcements",
  "nav.compact.attendance",
  "nav.compact.grades",
  "nav.compact.library",
  "nav.compact.permits",
  "nav.compact.profile",
  "nav.discipline.items.counseling",
  "nav.discipline.items.reports",
  "nav.discipline.items.violations",
  "nav.discipline.items.warningLetters",
  "nav.discipline.label",
  "nav.finance.label",
  "nav.home",
  "nav.library.items.catalog",
  "nav.library.items.circulation",
  "nav.library.items.members",
  "nav.library.items.opac",
  "nav.library.items.reports",
  "nav.library.items.stockOpname",
  "nav.library.items.visits",
  "nav.library.label",
  "nav.mentoring.label",
  "nav.permits.items.exitPermit",
  "nav.permits.items.gate",
  "nav.permits.items.late",
  "nav.permits.items.plannedLeave",
  "nav.permits.items.verification",
  "nav.permits.label",
  "nav.platform.items.tenants",
  "nav.platform.label",
  "nav.schoolData.items.academicCalendar",
  "nav.schoolData.items.academicYear",
  "nav.schoolData.items.assignments",
  "nav.schoolData.items.classesAndStudents",
  "nav.schoolData.items.enrollmentImport",
  "nav.schoolData.items.gradeLevels",
  "nav.schoolData.items.newYearSetup",
  "nav.schoolData.items.periods",
  "nav.schoolData.items.promotion",
  "nav.schoolData.items.rooms",
  "nav.schoolData.items.subjectOfferings",
  "nav.schoolData.items.subjects",
  "nav.schoolData.items.teachersAndStaff",
  "nav.schoolData.items.teachingAssignments",
  "nav.schoolData.items.tracks",
  "nav.schoolData.items.violationCatalog",
  "nav.schoolData.label",
  "nav.settings.items.documentTemplates",
  "nav.settings.items.integrations",
  "nav.settings.items.modules",
  "nav.settings.items.policies",
  "nav.settings.items.rolesAndAccess",
  "nav.settings.items.schoolProfile",
  "nav.settings.items.sessionsAndSecurity",
  "nav.settings.label",
  "nav.supervision.label",
  "nav.visitors.items.board",
  "nav.visitors.items.expected",
  "nav.visitors.items.incidents",
  "nav.visitors.items.reports",
  "nav.visitors.label",
  "validation.email",
  "validation.maxLength",
  "validation.minLength",
  "validation.passwordMax",
  "validation.passwordMin",
  "validation.passwordMismatch",
  "validation.passwordRequired",
  "validation.required",
  "validation.tenantQueryMin",
  "validation.usernameRequired",
];
