// Package service implements the platform console's use cases: listing
// tenants with a health summary, provisioning a tenant and its first
// admin, suspend/resume, custom domains, per-tenant module flags, and
// tenant data exports. Every method refuses outright when the deployment
// runs in single-tenant mode (docs/12-roadmap.md Fase 3).
package service

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/riverqueue/river"
	"github.com/riverqueue/river/rivertype"

	"github.com/omanjaya/newsekolah/apps/api/internal/modules/platform/domain"
	"github.com/omanjaya/newsekolah/apps/api/internal/platform/clock"
	"github.com/omanjaya/newsekolah/apps/api/internal/platform/config"
	"github.com/omanjaya/newsekolah/apps/api/internal/platform/database"
)

// Repository is the platform module's data-access boundary.
type Repository interface {
	ListTenants(ctx context.Context) ([]domain.Tenant, error)
	GetTenant(ctx context.Context, id uuid.UUID) (domain.Tenant, bool, error)
	CreateTenant(ctx context.Context, in domain.TenantInput) (domain.Tenant, error)
	UpdateTenantStatus(ctx context.Context, id uuid.UUID, status domain.TenantStatus) (domain.Tenant, bool, error)
	UpdateTenantDomain(ctx context.Context, id uuid.UUID, host string) (domain.Tenant, bool, error)

	CountUsers(ctx context.Context, tenantID uuid.UUID) (int, error)
	ActiveAcademicYearLabel(ctx context.Context, tenantID uuid.UUID) (string, bool, error)
	LastActivityAt(ctx context.Context, tenantID uuid.UUID) (*time.Time, error)

	ListFeatureFlags(ctx context.Context, tenantID uuid.UUID) ([]domain.ModuleFlag, error)
	SetFeatureFlag(ctx context.Context, tenantID uuid.UUID, module domain.Module, enabled bool) (domain.ModuleFlag, error)

	CreateExport(ctx context.Context, tenantID uuid.UUID) (domain.Export, error)
	GetExport(ctx context.Context, tenantID, exportID uuid.UUID) (domain.Export, bool, error)
	UpdateExportStatus(ctx context.Context, exportID uuid.UUID, status domain.ExportStatus, objectKey, errMsg string, completedAt *time.Time) error

	ExportUsersCSV(ctx context.Context, tenantID uuid.UUID) ([][]string, error)
	ExportAcademicYearsCSV(ctx context.Context, tenantID uuid.UUID) ([][]string, error)
	ExportClassesCSV(ctx context.Context, tenantID uuid.UUID) ([][]string, error)
}

// AdminInput is what the console asks for about a new tenant's first
// administrator; the password is generated by the provisioner and
// returned exactly once.
type AdminInput struct {
	Username string
	Email    string
	Name     string
}

// AdminResult is handed back to the caller once, immediately after
// provisioning; nothing stores the plaintext password after that.
type AdminResult struct {
	UserID   uuid.UUID
	Username string
	Password string
}

// IdentityProvisioner is what the platform module needs from identity:
// create the tenant's first administrator with every permission a tenant
// admin needs. Implemented by an adapter in apps/api/internal/wiring so
// this package never imports identity internals directly.
type IdentityProvisioner interface {
	ProvisionAdmin(ctx context.Context, tenantID uuid.UUID, in AdminInput) (AdminResult, error)

	// EnsureTenantDefaults creates every system role (teacher, staff,
	// student, parent, librarian, principal -- ProvisionAdmin above
	// already created "admin"), default duty type (homeroom, counselor,
	// leadership, security, picket, librarian), and default library
	// member type the tenant does not already have, from
	// internal/platform/migrator.EnsureTenantDefaults, so a new tenant is
	// immediately usable instead of only after someone runs the relevant
	// admin UI by hand for each one, or waits for a deploy's migrate run.
	EnsureTenantDefaults(ctx context.Context, tenantID uuid.UUID) error
}

// JobInserter is the slice of *river.Client[pgx.Tx] RequestExport needs:
// enqueue the export job in the same transaction as the tenant_exports row
// it belongs to. Matched structurally so tests can supply a fake.
type JobInserter interface {
	InsertTx(ctx context.Context, tx pgx.Tx, args river.JobArgs, opts *river.InsertOpts) (*rivertype.JobInsertResult, error)
}

// Storage is the object-storage slice the export job needs: write the ZIP
// once, then hand back a time-limited link to it.
type Storage interface {
	PutObject(ctx context.Context, objectKey string, content []byte, contentType string) error
	PresignedGetURL(ctx context.Context, objectKey string, ttl time.Duration) (string, error)
}

type Service struct {
	pool    *pgxpool.Pool
	repo    Repository
	admin   IdentityProvisioner
	jobs    JobInserter
	storage Storage
	clock   clock.Clock
	mode    config.TenancyMode
	bucket  string
}

func New(pool *pgxpool.Pool, repo Repository, admin IdentityProvisioner, jobs JobInserter, storage Storage, clk clock.Clock, mode config.TenancyMode, bucket string) *Service {
	return &Service{pool: pool, repo: repo, admin: admin, jobs: jobs, storage: storage, clock: clk, mode: mode, bucket: bucket}
}

// guard refuses every operation outright in single-tenant mode: one school
// deployment has exactly one tenant and no console to operate on.
func (s *Service) guard() error {
	if s.mode == config.TenancySingle {
		return domain.ErrTenancyDisabled
	}
	return nil
}

// withTx opens the tenant-scoped transaction for one use case, per
// docs/03-layered-architecture.md section 2.
func (s *Service) withTx(ctx context.Context, tenantID uuid.UUID, fn func(ctx context.Context) error) error {
	return database.WithTenantTx(ctx, s.pool, tenantID, fn)
}

// withPlatformTx opens the cross-tenant transaction for a use case that
// runs before any one tenant exists to scope a transaction to -- CreateTenant
// is the only caller today. A nested WithTenantTx call made from inside fn
// (e.g. identity's own s.withTx while provisioning the new tenant's admin)
// joins this same transaction instead of opening a second one: see
// database.withTx's ambient-transaction reuse and WithTenantTx's per-call
// set_config, which re-scopes app.tenant_id to the callee's own tenant id
// even when joining an existing transaction.
func (s *Service) withPlatformTx(ctx context.Context, fn func(ctx context.Context) error) error {
	return database.WithPlatformTx(ctx, s.pool, fn)
}

func txFromContext(ctx context.Context) (pgx.Tx, bool) {
	return database.TxFromContext(ctx)
}
